image: ameysunu/flutterdocker

stages:          # List of stages for jobs, and their order of execution
  - test
  # - build
  # - deploy

flutter_test: 
  stage: test 
  script:
    - flutter test 

# build_android:
#   stage: build
#   script:

# build_ios:
#   stage: build
#   script:

# deploy_android:
#   stage: deploy
#   script:

# deploy_ios:
#   stage: deploy
#   script:

