# image: haizen/flutter
# image: fischerscode/flutter

stages:          # List of stages for jobs, and their order of execution
  - test
  - build
  # - deploy

flutter_test:
  stage: test
  image: haizen/flutter
  script:
    - flutter test

build_android:
  stage: build
  image: matsp/docker-flutter
  before_script:
    - flutter packages get
    - flutter clean
  script:
     - flutter build apk --release
  artifacts:
    paths:
      - build/app/outputs/apk/release/app-release.apk

build_ios:
  stage: build
  image: matsp/docker-flutter
  before_script:
    - flutter packages get
    - flutter clean
  script:
    - flutter build ipa
    - cd ios
    - xcodebuild clean archive -workspace Runner.xcworkspace -scheme Runner -archivePath RunnerArchive
    - xcodebuild -exportArchive -archivePath RunnerArchive.xcarchive -exportOptionsPlist ExportOptions.plist -exportPath ./build
  artifacts:
    paths:
      - ios/build/Runner.ipa

# deploy_android:
#   stage: deploy
#   script:

# deploy_ios:
#   stage: deploy
#   script:
