image: ameysunu/flutterdocker

stages:          # List of stages for jobs, and their order of execution
  - test
  - build
  # - deploy

flutter_test: 
  stage: test 
  script:
    - flutter test 

build_android:
  stage: build
  before_script:
    - flutter packages get
    - flutter clean
  script:
     - flutter build apk
  artifacts:
    paths:
      - build/app/outputs/apk/release/app-release.apk

build_ios:
  stage: build
  before_script:
    - flutter packages get
    - flutter clean
  script:
    - flutter build ios --release
    - cd ios
    - xcodebuild clean archive -workspace Runner.xcworkspace -scheme Runner -archivePath RunnerArchive
    - xcodebuild -exportArchive -archivePath RunnerArchive.xcarchive -exportOptionsPlist ExportOptions.plist -exportPath ./build
  artifacts:
    paths:
      - ios/build/Runner.ipa

# deploy_android:
#   stage: deploy
#   script:

# deploy_ios:
#   stage: deploy
#   script:

